version: "3"
services:
  workspace:
    image: mcr.microsoft.com/vscode/devcontainers/universal:1-focal
    init: true
    volumes:
      - workspace:/app

  web:
    image: craftcms/nginx:8.1-dev
    volumes:
      - workspace:/app
    ports:
      - 80:8080
    environment:
      CRAFT_ENVIRONMENT: dev
      CRAFT_DB_DRIVER: pgsql
      CRAFT_DB_SERVER: db
      CRAFT_DB_DATABASE: db
      CRAFT_DB_USER: db
      CRAFT_DB_PASSWORD: db

  db:
    image: postgres:13
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

volumes:
  db:
  workspace:
