version: "3"
services:
  workspace:
    image: craftcms/cli:8.1-dev
    volumes:
      - .:/app
    network_mode: service:web
    depends_on:
      db:
        condition: service_healthy

  web:
    image: craftcms/nginx:8.1-dev
    volumes:
      - .:/app
    ports:
      - 80:8080

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended in production:
    # https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 10

volumes:
  db:
