version: "3"
services:
  workspace:
    # image: mcr.microsoft.com/devcontainers/php:0-8.2
    image: craftcms/cli:8.1-dev
    volumes:
      - .:/app
      # - ..:/workspaces:cached
    tty: true
    network_mode: service:web
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    image: craftcms/nginx:8.1-dev
    volumes:
      - .:/app
    ports:
      - 8080:8080

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended in production:
    # https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5

  # db:
  #   image: postgres:13
  #   restart: unless-stopped
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - db:/var/lib/postgresql/data:delegated
  #   environment:
  #     POSTGRES_DB: db
  #     POSTGRES_USER: db
  #     POSTGRES_PASSWORD: db
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "db", "-d", "db"]
  #     interval: 5s
  #     retries: 3

  # redis:
  #   image: redis:6-alpine
  #   ports:
  #     - 6379:6379
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]

volumes:
  db:
