version: "3"
services:
  app:
    image: craftcms/nginx:8.1-dev
    volumes:
      - ../:/app:cached
    ports:
      - 80:80
    environment:
      CRAFT_ENVIRONMENT: dev
      CRAFT_DB_DRIVER: pgsql
      CRAFT_DB_SERVER: db
      CRAFT_DB_DATABASE: db
      CRAFT_DB_USER: db
      CRAFT_DB_PASSWORD: db

  db:
    image: postgres:13
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
